test/main_test.cpp File Reference
#include "../external/doctest/doctest.h"
Macros
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Functions
int add (int a, int b)
int subtract (int a, int b)
TEST_CASE ("Addition works correctly")
TEST_CASE ("Subtraction works correctly")
Macro Definition Documentation
DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
Definition at line 1 of file main_test.cpp.
Function Documentation
add()
int add (int a, int b)
Definition at line 5 of file main_test.cpp.
Referenced by TEST_CASE().
subtract()
int subtract (int a, int b)
Definition at line 9 of file main_test.cpp.
Referenced by TEST_CASE().
TEST_CASE() [1/2]
TEST_CASE ("Addition works correctly")
Definition at line 13 of file main_test.cpp.
References add().
TEST_CASE() [2/2]
TEST_CASE ("Subtraction works correctly")
Definition at line 19 of file main_test.cpp.
References subtract().