name: Sync Main Dirs into Docs Branch

on:
  push:
    branches: [docs]
  workflow_dispatch:

permissions:
  contents: write  # Required to allow git push

jobs:
  sync-main-dirs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout docs branch
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git pull origin main

    - name: Extract src/include/test/external from main into docs branch
      run: |
        for dir in src include test external; do
          git archive origin/main $dir | tar -x
        done

    - name: Commit and push changes to docs branch
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add src include test external
        git commit -m "Add src/include/test/external from main to docs" || echo "No changes to commit"
        git push
