name: Sync and Build Docs

on:
  push:
    branches: [docs]
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout docs branch
      uses: actions/checkout@v4

    - name: Fetch origin/main
      run: git fetch origin main

    - name: Pull specific directories from main
      run: |
        for dir in src include test external; do
          git archive origin/main $dir | tar -x
        done

    - name: Confirm docker-compose.yml exists
      run: test -f docker-compose.yml && echo "Found docker-compose.yml"

    - name: Run Docker Compose
      run: sudo docker compose up --build -d
      
    - name: Commit and push updated dirs
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git restore --staged docs && git restore docs  # <-- prevent deleting docs/
        git add src include test external
        git commit -m "Update dirs from main" || echo "No changes to commit"
        git push
