name: Sync Main Dirs into Docs

on:
  push:
    branches: [docs]
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  sync-main-dirs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout docs branch
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main

    - name: Extract specific directories from main
      run: |
        for dir in src include test external; do
          git archive origin/main $dir | tar -x
        done

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add src include test external
        git commit -m "Sync dirs from main" || echo "No changes to commit"
        git push
